baseURL = ""
languageCode = "en-us"
title = "Opencellsoft"

[params]

  [params.navbar]
    [params.navbar.url]
      platform   = "#"
      solution    = "#"
      support     = "#"
      getADemo    = "#"
      logIn       = "/admin"
      aboutUs     = "#"
      story       = "/aboutus/story/"
      businessModel = "/aboutus/businessmodel/"
      customers = "/aboutus/customers/"
      partners = "/aboutus/partners/"
      workplaceAndJobs = "/aboutus/workplaceandjobs/"
  adminUrl = "/admin"
