baseURL = ""
languageCode = "en-us"
title = "Opencellsoft"

[params]
  [params.navbar]
    [params.navbar.url]
      platform   = "#"
      solution    = "#"
      support     = "#"
      getADemo    = "#"
      logIn       = "/admin"
      aboutUs     = "/aboutus/pressreleases/"
      story       = "/aboutus/story/"
      businessModel = "/aboutus/businessmodel/"
      customers = "/aboutus/customers/"
      partners = "/aboutus/partners/"
      workplaceAndJobs = "/aboutus/workplaceandjobs/"
      byindustry = "/solution/byindustry/"
      byrole = "/solution/byrole/"
      modules = "/platform/modules/"
      technology = "/platform/technology/"
      ecosystem = "/platform/ecosystem/"
  adminUrl = "/admin"
  [params.url]
    getInTouch  = "#"
    getDemo  = "#"
