backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: test # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

display_url: https://opencell-test.netlify.com/
logo_url: /img/logo-opencell.svg

collections:
  - name: "indexpage"
    label: "Index Page"
    files:
      - name: "header"
        label: "Header"
        file: "data/indexpage/header.yml"
        fields:
          - label: Carousel
            name: carousel
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
      - name: "paradigm"
        label: "A new paradigm"
        file: "data/indexpage/paradigm.yml"
        fields:
          - {label: Youtube Id, name: video, widget: string}
      - name: "whatweprovide"
        label: "What we provide"
        file: "data/indexpage/whatweprovide.yml"
        fields:
          - {label: Content, name: content, widget: markdown}
          - {label: Image, name: image, widget: image}
      - name: "whatmakesus"
        label: "What makes us"
        file: "data/indexpage/whatmakesus.yml"
        fields:
          - label: Columns
            name: columns
            widget: list
            allow_add: false
            fields:
              - label: Title
                name: title
                widget: string
              - label: Content
                name: content
                widget: list
                allow_add: false
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Text
                    name: text
                    widget: string
      - name: "mainindustries"
        label: "Our main industries"
        file: "data/indexpage/mainindustries.yml"
        fields:
          - {label: "Subtitle", name: "subtitle", widget: string}
          - {label: "Block 1", name: "block1", widget: string}
          - {label: "Block 2", name: "block2", widget: string}
          - {label: "Block 3", name: "block3", widget: string}
          - {label: "Block 4 ", name: "block4", widget: string}
      - name: "ourcustomers"
        label: "Our customers."
        file: "data/indexpage/ourcustomers.yml"
        fields:
          - label: Logos
            name: logos
            widget: list
            allow_add: true
            fields:
              - label: Logo
                name: url
                widget: image
              - label: Alternative
                name: alt
                widget: string
      - name: "worktogether"
        label: "We work together"
        file: "data/indexpage/worktogether.yml"
        fields:
          - label: Testimonials
            name: testimonials
            widget: list
            allow_add: true
            fields:
            - {label: "Testimonial", name: "testimonial", widget: string}
            - {label: "Author", name: "author", widget: string}
      - name: "learnmore"
        label: "Learn more"
        file: "data/indexpage/learnmore.yml"
        fields:
          - {label: "Video Id 1", name: "video1", widget: string}
          - {label: "Video Id 2", name: "video2", widget: string}
  - label: "Metadatas"
    name: "metadatas"
    files:
    - label: "All Pages"
      name: "allpagesmetadatas"
      file: "data/metadatas/allpages.yml"
      fields:
      - label: "Metadatas"
        name: metadatas
        widget: list
        fields:
        - {label: 'Name', name: 'name', widget: string}
        - {label: 'Content', name: 'content', widget: string}
  - label: About Us
    name: aboutus
    files:
      - label: Press Releases (About us main page)
        name: pressreleases
        file: data/aboutus/pressreleases.yml
        fields:
          - label: Articles
            name: articles
            widget: list
            fields:
              - { label: Month of release, name: month, widget: string }
              - { label: Year of release, name: year, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Article Link, name: url, widget: string }
      - label: About us - Story Page
        name: aboutusstory
        file: data/aboutus/story.yml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Description, name: description, widget: text, required: false }
          - label: Our Story Section
            name: ourstory
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: text }
              - label: Boxes
                name: boxes
                widget: list
                fields:
                  - { label: Content, name: content, widget: text }
          - label: Investors Section
            name: investors
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Investors
                name: logos
                widget: list
                fields:
                  - { label: Alternative Text (name), name: alt, widget: string }
                  - { label: Logo, name: url, widget: image }
          - label: Partners Section
            name: partners
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Partners
                name: logos
                widget: list
                fields:
                  - { label: Alternative Text (name), name: alt, widget: string }
                  - { label: Logo, name: url, widget: image }
          - label: Leadership Section
            name: leadership
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Leaders
                name: leaders
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Position, name: position, widget: string }
                  - { label: Photo, name: url, widget: image }
      - label: About us - Business Model
        name: aboutusbusinessmodel
        file: data/aboutus/businessmodel.yml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Description, name: description, widget: text, required: false }
          - label: Introduction paragraph
            name: introduction
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: text }
          - label: Boxes
            name: boxes
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Icon
                name: url
                widget: image
      - label: About us - Customers
        name: aboutuscustomers
        file: data/aboutus/customers.yml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Description, name: description, widget: text, required: false }
          - label: Introduction paragraph
            name: introduction
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: text }
          - label: Sections
            name: sections
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - logos: Logos
                name: logos
                widget: list
                fields:
                  - label: Alternative Text (Name)
                    name: alt
                    widget: string
                  - label: Logo
                    name: url
                    widget: image
      - label: About us - Workplace & jobs
        name: aboutusworkplaceandjobs
        file: data/aboutus/workplaceandjobs.yml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Description, name: description, widget: text, required: false }
          - label: Introduction paragraph
            name: introduction
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: text }
              - label: Image
                name: img
                widget: object
                fields:
                  - { label: Image, name: url, widget: image }
                  - { label: Alternative Text, name: alt, widget: string }
  - label: Job offers
    name: joboffers
    folder: content/jobs
    create: true
    fields:
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: Short description, name: description, widget: string }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
