backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

display_url: https://opencell-test.netlify.com/admin
logo_url: https:/opencell-test.netlify.com/img/logo-opencell.svg

collections:
  - name: "indexpage"
    label: "Index Page"
    files:
      - name: "paradigm"
        label: "A new paradigm"
        file: "data/indexpage/paradigm.yml"
        fields:
          - {label: Youtube URL, name: youtubeurl, widget: string}
      - name: "whatweprovide"
        label: "What we provide"
        file: "data/indexpage/whatweprovide.yml"
        fields:
          - {label: Content, name: content, widget: markdown}
          - {label: Image, name: image, widget: image}
      - name: "whatmakesus"
        label: "What makes us"
        file: "data/indexpage/whatmakesus.yml"
        fields:
          - {label: "Title 1", name: "title1", widget: string }
          - {label: "Subtitle 1-1", name: "subtitle-1-1", widget: string}
          - {label: "Text 1-1", name: "text-1-1", widget: string}
          - {label: "Subtitle 1-2", name: "subtitle-1-2", widget: string}
          - {label: "Text 1-2", name: "text-1-2", widget: string}
          - {label: "Subtitle 1-3", name: "subtitle-1-3", widget: string}
          - {label: "Text 1-3", name: "text-1-3", widget: string}
          - {label: "Subtitle 1-4", name: "subtitle-1-4", widget: string}
          - {label: "Text 1-4", name: "text-1-4", widget: string}
          - {label: "Title 2", name: "title2", widget: string }
          - {label: "Subtitle 2-1", name: "subtitle-2-1", widget: string}
          - {label: "Text 2-1", name: "text-2-1", widget: string}
          - {label: "Subtitle 2-2", name: "subtitle-2-2", widget: string}
          - {label: "Text 2-2", name: "text-2-2", widget: string}
          - {label: "Subtitle 2-3", name: "subtitle-2-3", widget: string}
          - {label: "Text 2-3", name: "text-2-3", widget: string}
          - {label: "Subtitle 2-4", name: "subtitle-2-4", widget: string}
          - {label: "Text 2-4", name: "text-2-4", widget: string}
          - {label: "Title 3", name: "title3", widget: string }
          - {label: "Subtitle 3-1", name: "subtitle-3-1", widget: string}
          - {label: "Text 3-1", name: "text-3-1", widget: string}
          - {label: "Subtitle 3-2", name: "subtitle-3-2", widget: string}
          - {label: "Text 3-2", name: "text-3-2", widget: string}
          - {label: "Subtitle 3-3", name: "subtitle-3-3", widget: string}
          - {label: "Text 3-3", name: "text-3-3", widget: string}
          - {label: "Subtitle 3-4", name: "subtitle-3-4", widget: string}
          - {label: "Text 3-4", name: "text-3-4", widget: string}
      - name: "mainindustries"
        label: "Our main industries"
        file: "data/indexpage/mainindustries.yml"
        fields:
          - {label: "Subtitle", name: "subtitle", widget: string}
          - {label: "Block 1", name: "block1", widget: string)
          - {label: "Block 2", name: "block2", widget: string)
          - {label: "Block 3", name: "block3", widget: string)
          - {label: "Block 4", name: "block4", widget: string)
      - name: "ourcustomers"
        label: "Our customers."
        file: "data/indexpage/ourcustomers.yml"
        fields:
          - {label: "Logo 1", name: "logo1", widget: image}
          - {label: "Logo 2", name: "logo2", widget: image)
          - {label: "Logo 3", name: "logo3", widget: image)
          - {label: "Logo 4", name: "logo4", widget: image)
          - {label: "Logo 5", name: "logo5", widget: image)
          - {label: "Logo 6", name: "logo6", widget: image)
          - {label: "Logo 7", name: "logo7", widget: image)
          - {label: "Logo 8", name: "logo8", widget: image)
      - name: "worktogether"
        label: "We work together"
        file: "data/indexpage/worktogether.yml"
        fields:
          - {label: "Testimonial 1", name: "testimonial1", widget: string}
          - {label: "Author 1", name: "author1", widget: string}
          - {label: "Testimonial 2", name: "testimonial2", widget: string}
          - {label: "Author 2", name: "author2", widget: string}
          - {label: "Testimonial 3", name: "testimonial3", widget: string}
          - {label: "Author 3", name: "author3", widget: string}
      - name: "learnmore"
        label: "Learn more"
        file: "data/indexpage/leanmore.yml"
        fields:
          - {label: "Video 1", name: "video1", widget: string}
          - {label: "Video 2", name: "video2", widget: string}
