backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

display_url: https://opencell-test.netlify.com/admin
logo_url: https:/opencell-test.netlify.com/img/logo-opencell.svg

collections:
  - name: "testimonials"
    label: "Testimonials" # Used in the UI
    folder: "content/testimonials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ['.{3,}', "Must have at least 3 characters"]
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Testimonial", name: "testimonial", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}

  - name: "indexpage"
    label: "Index Page"
    files:
      - name: "whatweprovide"
        label: "What we provide"
        file: "data/indexpage/whatweprovide.yml"
        fields:
          - {label: Content, name: content, widget: markdown}
          - {label: Image, name: image, widget: image}
      - name: "whatmakesus"
        label: "What Makes Us"
        file: "data/indexpage/whatmakesus.yml"
        fields:
          - {label: "Title 1", name: "title1", widget: string }
          - {label: "Subtitle 1-1", name: "subtitle-1-1", widget: string}
          - {label: "Text 1-1", name: "text-1-1", widget: string}
          - {label: "Subtitle 1-2", name: "subtitle-1-2", widget: string}
          - {label: "Text 1-2", name: "text-1-2", widget: string}
          - {label: "Subtitle 1-3", name: "subtitle-1-3", widget: string}
          - {label: "Text 1-3", name: "text-1-3", widget: string}
          - {label: "Subtitle 1-4", name: "subtitle-1-4", widget: string}
          - {label: "Text 1-4", name: "text-1-4", widget: string}
          - {label: "Title 2", name: "title2", widget: string }
          - {label: "Subtitle 2-1", name: "subtitle-2-1", widget: string}
          - {label: "Text 2-1", name: "text-2-1", widget: string}
          - {label: "Subtitle 2-2", name: "subtitle-2-2", widget: string}
          - {label: "Text 2-2", name: "text-2-2", widget: string}
          - {label: "Subtitle 2-3", name: "subtitle-2-3", widget: string}
          - {label: "Text 2-3", name: "text-2-3", widget: string}
          - {label: "Subtitle 2-4", name: "subtitle-2-4", widget: string}
          - {label: "Text 2-4", name: "text-2-4", widget: string}
          - {label: "Title 3", name: "title3", widget: string }
          - {label: "Subtitle 3-1", name: "subtitle-3-1", widget: string}
          - {label: "Text 3-1", name: "text-3-1", widget: string}
          - {label: "Subtitle 3-2", name: "subtitle-3-2", widget: string}
          - {label: "Text 3-2", name: "text-3-2", widget: string}
          - {label: "Subtitle 3-3", name: "subtitle-3-3", widget: string}
          - {label: "Text 3-3", name: "text-3-3", widget: string}
          - {label: "Subtitle 3-4", name: "subtitle-3-4", widget: string}
          - {label: "Text 3-4", name: "text-3-4", widget: string}
          - {label: "Title 4", name: "title4", widget: string }
          - {label: "Subtitle 4-1", name: "subtitle-4-1", widget: string}
          - {label: "Text 4-1", name: "text-4-1", widget: string}
          - {label: "Subtitle 4-2", name: "subtitle-4-2", widget: string}
          - {label: "Text 4-2", name: "text-4-2", widget: string}
          - {label: "Subtitle 4-3", name: "subtitle-4-3", widget: string}
          - {label: "Text 4-3", name: "text-4-3", widget: string}
          - {label: "Subtitle 4-4", name: "subtitle-4-4", widget: string}
          - {label: "Text 4-4", name: "text-4-4", widget: string}
