backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: test # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

display_url: https://opencell-test.netlify.com/
logo_url: /img/logo-opencell.svg

collections:
  - label: Pages
    name: pages
    files:
      - label: Index
        name: index
        file: content/_index.md
        fields:
        - label: Header
          name: header
          widget: object
          fields:
            - label: Carousel
              name: carousel
              widget: list
              fields:
                - label: Title
                  name: title
                  widget: string
                - label: Subtitle
                  name: subtitle
                  widget: string
        - label: Paradigm
          name: paradigm
          widget: object
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Youtube Id, name: videoId, widget: string}
        - label: What we provide
          name: whatweprovide
          widget: object
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Content, name: content, widget: text}
            - {label: Image, name: image, widget: image}
            - {label: Button, name: button, widget: string, default: DISCOVER}
        - label: What makes us
          name: whatmakesus
          widget: object
          fields:
            - {label: Title, name: title, widget: string}
            - label: Columns
              name: columns
              widget: list
              allow_add: false
              fields:
                - {label: Title, name: title, widget: string}
                - label: Content
                  name: content
                  widget: list
                  allow_add: false
                  fields:
                    - {label: Title, name: title, widget: string}
                    - {label: Text, name: text, widget: string}
        - label: Our main industries
          name: mainindustries
          widget: object
          fields:
            - {label: Subtitle, name: subtitle, widget: string}
            - {label: Block 1, name: block1, widget: string}
            - {label: Block 2, name: block2, widget: string}
            - {label: Block 3, name: block3, widget: string}
            - {label: Block 4, name: block4, widget: string}
        - label: Our customers
          name: ourcustomers
          widget: object
          fields:
            - {label: Title, name: title, widget: string}
            - label: Logos
              name: logos
              widget: list
              allow_add: true
              fields:
                - {label: Logo, name: url, widget: image}
                - {label: Alternative, name: alt, widget: string}
        - label: We work together
          name: worktogether
          widget: object
          fields:
            - {label: Title, name: title, widget: string}
            - label: Testimonials
              name: testimonials
              widget: list
              allow_add: true
              fields:
              - {label: Testimonial, name: testimonial, widget: string}
              - {label: Author, name: author, widget: string}
        - label: Learn more
          name: learnmore
          widget: object
          fields:
            - label: Videos
              name: videoIds
              widget: list
              fields:
                - {label: "Video Id", name: "videoId", widget: string}
        - {label: Markdown, name: body, widget: hidden}
  - label: About Us
    name: aboutus
    files:
      - label: Press Releases (Main About us page)
        name: pressreleases
        file: content/aboutus/pressreleases.md
        fields:
          - {label: Layout, name: layout, widget: hidden, default: pressreleases}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Articles
            name: articles
            widget: list
            fields:
              - {label: Date of release, name: date, widget: date}
              - {label: Description, name: description, widget: string}
              - {label: Article Link, name: url, widget: string}
              - {label: Button, name: button, widget: string, default: READ}
          - {label: Markdown, name: body, widget: hidden}
      - label: Story Page
        name: aboutusstory
        file: content/aboutus/story.md
        fields:
          - {label: Layout, name: layout, widget: hidden, default: story}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Description, name: description, widget: text, required: false}
          - label: Our Story Section
            name: ourstory
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: text}
              - label: Boxes
                name: boxes
                widget: list
                fields:
                  - {label: Content, name: content, widget: string}
          - label: Investors Section
            name: investors
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Investors
                name: logos
                widget: list
                fields:
                  - {label: Alternative, name: alt, widget: string}
                  - {label: Logo, name: url, widget: image}
          - label: Partners Section
            name: partners
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Partners
                name: logos
                widget: list
                fields:
                  - { label: Alternative, name: alt, widget: string }
                  - { label: Logo, name: url, widget: image }
          - label: Leadership Section
            name: leadership
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Leaders
                name: leaders
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Position, name: position, widget: string}
                  - {label: Photo, name: url, widget: image}
          - {label: Markdown, name: body, widget: hidden}
      - label: Business Model
        name: aboutusbusinessmodel
        file: content/aboutus/businessmodel.md
        fields:
          - {label: Layout, name: layout, widget: hidden, default: businessmodel}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Description, name: description, widget: text, required: false}
          - label: Introduction paragraph
            name: introduction
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: text }
          - label: Boxes
            name: boxes
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Icon, name: url, widget: image}
          - {label: Markdown, name: body, widget: hidden}
      - label: Customers
        name: aboutuscustomers
        file: content/aboutus/customers.md
        fields:
          - {label: Layout, name: layout, widget: hidden, default: customers}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Description, name: description, widget: text, required: false}
          - label: Introduction paragraph
            name: introduction
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: text}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - logos: Logos
                name: logos
                widget: list
                fields:
                  - {label: Alternative, name: alt, widget: string}
                  - {label: Logo, name: url, widget: image}
          - {label: Markdown, name: body, widget: hidden}
      - label: Workplace & jobs
        name: aboutusworkplaceandjobs
        file: content/aboutus/workplaceandjobs.md
        fields:
          - {label: Layout, name: layout, widget: hidden, default: workplaceandjobs}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Description, name: description, widget: text, required: false}
          - label: Introduction paragraph
            name: introduction
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: text}
              - label: Image
                name: img
                widget: object
                fields:
                  - {label: Image, name: url, widget: image}
                  - {label: Alternative Text, name: alt, widget: string}
          - {label: Markdown, name: body, widget: hidden}
  - label: "Metadatas"
    name: "metadatas"
    files:
    - label: "All Pages"
      name: "allpagesmetadatas"
      file: "data/metadatas/allpages.yml"
      fields:
      - label: "Metadatas"
        name: metadatas
        widget: list
        fields:
        - {label: 'Name', name: 'name', widget: string}
        - {label: 'Content', name: 'content', widget: string}

  - label: Job offers
    name: joboffers
    folder: content/jobs
    create: true
    fields:
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: Short description, name: description, widget: string }
      - { label: Button Name, name: button, widget: string, default: APPLY }
      - { label: "Body", name: "body", widget: "markdown" }
