backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

display_url: https://opencell-test.netlify.com/
logo_url: https:/opencell-test.netlify.com/img/logo-opencell.svg

collections:
  - name: "indexpage"
    label: "Index Page"
    files:
      - name: "header"
        label: "Header"
        file: "data/indexpage/header.yml"
        fields:
          - {label: Title 1, name: title1, widget: string}
          - {label: Subtitle2, name: subtitle1, widget: string}
          - {label: Title 2, name: title2, widget: string}
          - {label: Subtitle 2, name: subtitle2, widget: string}
          - {label: Title 3, name: title3, widget: string}
          - {label: Subtitle 3, name: subtitle3, widget: string}
      - name: "paradigm"
        label: "A new paradigm"
        file: "data/indexpage/paradigm.yml"
        fields:
          - {label: Youtube Id, name: video, widget: string}
      - name: "whatweprovide"
        label: "What we provide"
        file: "data/indexpage/whatweprovide.yml"
        fields:
          - {label: Content, name: content, widget: markdown}
          - {label: Image, name: image, widget: image}
      - name: "whatmakesus"
        label: "What makes us"
        file: "data/indexpage/whatmakesus.yml"
        fields:
          - {label: "Title 1", name: "title1", widget: string }
          - {label: "Subtitle 1-1", name: "subtitle_1_1", widget: string}
          - {label: "Text 1-1", name: "text_1_1", widget: string}
          - {label: "Subtitle 1-2", name: "subtitle_1_2", widget: string}
          - {label: "Text 1-2", name: "text_1_2", widget: string}
          - {label: "Subtitle 1-3", name: "subtitle_1_3", widget: string}
          - {label: "Text 1-3", name: "text_1_3", widget: string}
          - {label: "Subtitle 1-4", name: "subtitle_1_4", widget: string}
          - {label: "Text 1-4", name: "text_1_4", widget: string}
          - {label: "Title 2", name: "title2", widget: string }
          - {label: "Subtitle 2-1", name: "subtitle_2_1", widget: string}
          - {label: "Text 2-1", name: "text_2_1", widget: string}
          - {label: "Subtitle 2-2", name: "subtitle_2_2", widget: string}
          - {label: "Text 2-2", name: "text_2_2", widget: string}
          - {label: "Subtitle 2-3", name: "subtitle_2_3", widget: string}
          - {label: "Text 2-3", name: "text_2_3", widget: string}
          - {label: "Subtitle 2-4", name: "subtitle_2_4", widget: string}
          - {label: "Text 2-4", name: "text_2_4", widget: string}
          - {label: "Title 3", name: "title3", widget: string }
          - {label: "Subtitle 3-1", name: "subtitle_3_1", widget: string}
          - {label: "Text 3-1", name: "text_3_1", widget: string}
          - {label: "Subtitle 3-2", name: "subtitle_3_2", widget: string}
          - {label: "Text 3-2", name: "text_3_2", widget: string}
          - {label: "Subtitle 3-3", name: "subtitle_3_3", widget: string}
          - {label: "Text 3-3", name: "text_3_3", widget: string}
          - {label: "Subtitle 3-4", name: "subtitle_3_4", widget: string}
          - {label: "Text 3-4", name: "text_3_4", widget: string}
      - name: "mainindustries"
        label: "Our main industries"
        file: "data/indexpage/mainindustries.yml"
        fields:
          - {label: "Subtitle", name: "subtitle", widget: string}
          - {label: "Block 1", name: "block1", widget: string}
          - {label: "Block 2", name: "block2", widget: string}
          - {label: "Block 3", name: "block3", widget: string}
          - {label: "Block 4 ", name: "block4", widget: string}
      - name: "ourcustomers"
        label: "Our customers."
        file: "data/indexpage/ourcustomers.yml"
        fields:
          - {label: "Logo 1", name: "logo1", widget: image}
          - {label: "Alternative text 1", name: "alt1", widget: string}
          - {label: "Logo 2", name: "logo2", widget: image}
          - {label: "Alternative text 2", name: "alt2", widget: string}
          - {label: "Logo 3", name: "logo3", widget: image}
          - {label: "Alternative text 3", name: "alt3", widget: string}
          - {label: "Logo 4", name: "logo4", widget: image}
          - {label: "Alternative text 4", name: "alt4", widget: string}
          - {label: "Logo 5", name: "logo5", widget: image}
          - {label: "Alternative text 5", name: "alt5", widget: string}
          - {label: "Logo 6", name: "logo6", widget: image}
          - {label: "Alternative text 6", name: "alt6", widget: string}
          - {label: "Logo 7", name: "logo7", widget: image}
          - {label: "Alternative text 7", name: "alt7", widget: string}
          - {label: "Logo 8", name: "logo8", widget: image}
          - {label: "Alternative text 8", name: "alt8", widget: string}
      - name: "worktogether"
        label: "We work together"
        file: "data/indexpage/worktogether.yml"
        fields:
          - {label: "Testimonial 1", name: "testimonial1", widget: string}
          - {label: "Author 1", name: "author1", widget: string}
          - {label: "Testimonial 2", name: "testimonial2", widget: string}
          - {label: "Author 2", name: "author2", widget: string}
          - {label: "Testimonial 3", name: "testimonial3", widget: string}
          - {label: "Author 3", name: "author3", widget: string}
      - name: "learnmore"
        label: "Learn more"
        file: "data/indexpage/learnmore.yml"
        fields:
          - {label: "Video Id 1", name: "video1", widget: string}
          - {label: "Video Id 2", name: "video2", widget: string}
  - label: "Metadatas"
    name: "metadatas"
    files:
    - label: "All Pages"
      name: "allpages"
      file: "data/metadatas/allpages.yml"
      fields:
      - label: "Metadatas"
        name: metadatas
        widget: list
        fields:
        - {label: 'Name', name: 'name', widget: string}
        - {label: 'Content', name: 'content', widget: string}
  - label: About Us
    name: aboutus
    files:
      - label: Our partners
        name: ourpartners
        file: data/aboutus/ourpartners.yml
        fields:
          - label: Title
            name: title
            widget: string
          - label: Logos
            name: logos
            widget: list
            allow_add: true
            fields:
              - label: Logo
                name: url
                widget: string
              - label: Alternative
                name: alt
                widget: string
