backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: test # Branch to update (optional; defaults to master)
  site_domain: cms.netlify.com

publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

display_url: https://opencell-test.netlify.com/
logo_url: /img/logo-opencell.svg

collections:
  - label: Our Blog - Articles
    name: "blogarticle"
    folder: "content/knowledgecenter/product/ourblog/articles"
    create: true
    fields:
      - {label: Type, name: type, widget: hidden, default: blogarticle}
      - {label: Draft,  name: draft, widget: select, options: ['true', 'false'], default: 'true'}
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - {label: Description, name: description, widget: text, required: false}
      - {label: Author, name: author, widget: string}
      - {label: Date, name: date, widget: date}
      - label: Tags
        name: articlestags
        widget: list
        required: false
      - {label: Thumbnail, name: thumbnail, widget: image}
      - {label: Body, name: body, widget: markdown}
  - label: Our Blog - Videos
    name: "blogvideo"
    folder: "content/knowledgecenter/product/ourblog/videos"
    create: true
    fields:
    - {label: Type, name: type, widget: hidden, default: blogvideo}
    - {label: Draft,  name: draft, widget: select, options: ['true', 'false'], default: 'true'}
    - {label: Title, name: title, widget: string}
    - {label: Subtitle, name: subtitle, widget: string}
    - {label: Description, name: description, widget: text, required: false}
    - {label: Author, name: author, widget: string}
    - {label: Date, name: date, widget: date}
    - label: Tags
      name: videostags
      widget: list
      required: false
    - {label: Video ID, name: videoid, widget: string}
    - {label: Body, name: body, widget: markdown}
  - label: Releases
    name: "releases"
    folder: "content/knowledgecenter/developer/releases"
    create: true
    fields:
    - {label: Type, name: type, widget: hidden, default: releases}
    - {label: Draft,  name: draft, widget: select, options: ['true', 'false'], default: 'true'}
    - {label: Title, name: title, widget: string}
    - {label: Subtitle, name: subtitle, widget: string}
    - {label: Description, name: description, widget: text, required: false}
    - {label: Author, name: author, widget: string}
    - {label: Date, name: date, widget: date}
    - label: Tags
      name: releasestags
      widget: list
      required: false
    - {label: Body, name: body, widget: markdown}
  - label: Releases Schedule
    name: "releaseschedule"
    folder: "content/knowledgecenter/developer/releaseschedule"
    create: true
    fields:
    - {label: Type, name: type, widget: hidden, default: releaseschedule}
    - {label: Draft,  name: draft, widget: select, options: ['true', 'false'], default: 'true'}
    - {label: Title, name: title, widget: string}
    - {label: Subtitle, name: subtitle, widget: string}
    - {label: Description, name: description, widget: text, required: false}
    - {label: Author, name: author, widget: string}
    - {label: Date, name: date, widget: date}
    - {label: Body, name: body, widget: markdown}
